name: PR CI
on:
  pull_request:

jobs:
  check-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      
      - uses: actions/setup-python@b64ffcaf5b410884ad320a9cfac8866006a109aa # v4.8.0
        with:
          python-version: '3.11'

      - name: install dev requirements
        run: make requirements-dev
      
      - name: check formatting
        run: make fmt-ci
  
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      
      - uses: actions/setup-python@b64ffcaf5b410884ad320a9cfac8866006a109aa # v4.8.0
        with:
          python-version: '3.11'

      - name: install requirements
        run: make requirements

      - name: install dev requirements
        run: make requirements-dev
     
      - name: run tests
        run: make test
      
